Hospital/Hospital/Controllers/citasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hospital.Models;

namespace Hospital.Controllers
{
    public class citasController : Controller
    {
        private hospitalEntities db = new hospitalEntities();

        // GET: citas
        public ActionResult Index()
        {
            var cita = db.cita.Include(c => c.empleado).Include(c => c.paciente);
            return View(cita.ToList());
        }

        // GET: citas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cita cita = db.cita.Find(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // GET: citas/Create
        public ActionResult Create()
        {
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre");
            ViewBag.idPaciente = new SelectList(db.paciente, "cedula", "nombre");
            return View();
        }

        // POST: citas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idCita,motivo,idEmpleado,idPaciente,fechaCita")] cita cita)
        {
            if (ModelState.IsValid)
            {
                db.cita.Add(cita);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", cita.idEmpleado);
            ViewBag.idPaciente = new SelectList(db.paciente, "cedula", "nombre", cita.idPaciente);
            return View(cita);
        }

        // GET: citas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cita cita = db.cita.Find(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", cita.idEmpleado);
            ViewBag.idPaciente = new SelectList(db.paciente, "cedula", "nombre", cita.idPaciente);
            return View(cita);
        }

        // POST: citas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idCita,motivo,idEmpleado,idPaciente,fechaCita")] cita cita)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cita).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", cita.idEmpleado);
            ViewBag.idPaciente = new SelectList(db.paciente, "cedula", "nombre", cita.idPaciente);
            return View(cita);
        }

        // GET: citas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cita cita = db.cita.Find(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // POST: citas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cita cita = db.cita.Find(id);
            db.cita.Remove(cita);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hospital/Hospital/Controllers/pacientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hospital.Models;

namespace Hospital.Controllers
{
    public class pacientesController : Controller
    {
        private hospitalEntities db = new hospitalEntities();

        // GET: pacientes
        public ActionResult Index()
        {
            var paciente = db.paciente.Include(p => p.tipoSangre1);
            return View(paciente.ToList());
        }

        // GET: pacientes/Details/5
        public ActionResult Details()
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //paciente paciente = db.paciente.Find(id);
            //if (paciente == null)
            //{
            //    return HttpNotFound();
            //}
            return View();
        }

        // GET: pacientes/Create
        public ActionResult Create()
        {
            ViewBag.tipoSangre = new SelectList(db.tipoSangre, "idSangre", "tipo");
            return View();
        }

        // POST: pacientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cedula,nombre,apellido,fechaNacimiento,tipoSangre,telefono")] paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.paciente.Add(paciente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.tipoSangre = new SelectList(db.tipoSangre, "idSangre", "tipo", paciente.tipoSangre);
            return View(paciente);
        }

        // GET: pacientes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paciente paciente = db.paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            ViewBag.tipoSangre = new SelectList(db.tipoSangre, "idSangre", "tipo", paciente.tipoSangre);
            return View(paciente);
        }

        // POST: pacientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cedula,nombre,apellido,fechaNacimiento,tipoSangre,telefono")] paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paciente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.tipoSangre = new SelectList(db.tipoSangre, "idSangre", "tipo", paciente.tipoSangre);
            return View(paciente);
        }

        // GET: pacientes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paciente paciente = db.paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }

        // POST: pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            paciente paciente = db.paciente.Find(id);
            db.paciente.Remove(paciente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hospital/Hospital/Controllers/recetasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hospital.Models;

namespace Hospital.Controllers
{
    public class recetasController : Controller
    {
        private hospitalEntities db = new hospitalEntities();

        // GET: recetas
        public ActionResult Index()
        {
            var receta = db.receta.Include(r => r.empleado).Include(r => r.paciente);
            return View(receta.ToList());
        }

        // GET: recetas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            receta receta = db.receta.Find(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            return View(receta);
        }

        // GET: recetas/Create
        public ActionResult Create()
        {
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre");
            ViewBag.idPaciente = new SelectList(db.paciente, "cedula", "nombre");
            return View();
        }

        // POST: recetas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idReceta,idPaciente,idEmpleado,fechaReceta,detalleReceta")] receta receta)
        {
            if (ModelState.IsValid)
            {
                db.receta.Add(receta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", receta.idEmpleado);
            ViewBag.idPaciente = new SelectList(db.paciente, "cedula", "nombre", receta.idPaciente);
            return View(receta);
        }

        // GET: recetas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            receta receta = db.receta.Find(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", receta.idEmpleado);
            ViewBag.idPaciente = new SelectList(db.paciente, "cedula", "nombre", receta.idPaciente);
            return View(receta);
        }

        // POST: recetas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idReceta,idPaciente,idEmpleado,fechaReceta,detalleReceta")] receta receta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(receta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", receta.idEmpleado);
            ViewBag.idPaciente = new SelectList(db.paciente, "cedula", "nombre", receta.idPaciente);
            return View(receta);
        }

        // GET: recetas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            receta receta = db.receta.Find(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            return View(receta);
        }

        // POST: recetas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            receta receta = db.receta.Find(id);
            db.receta.Remove(receta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hospital/Hospital/Controllers/visitasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hospital.Models;

namespace Hospital.Controllers
{
    public class visitasController : Controller
    {
        private hospitalEntities db = new hospitalEntities();

        // GET: visitas
        public ActionResult Index()
        {
            var visita = db.visita.Include(v => v.empleado).Include(v => v.receta);
            return View(visita.ToList());
        }

        // GET: visitas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visita visita = db.visita.Find(id);
            if (visita == null)
            {
                return HttpNotFound();
            }
            return View(visita);
        }

        // GET: visitas/Create
        public ActionResult Create()
        {
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre");
            ViewBag.idReceta = new SelectList(db.receta, "idReceta", "idPaciente");
            return View();
        }

        // POST: visitas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idVisita,idEmpleado,idReceta,fechaLlegada,proximaFecha,motivo,comentario")] visita visita)
        {
            if (ModelState.IsValid)
            {
                db.visita.Add(visita);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", visita.idEmpleado);
            ViewBag.idReceta = new SelectList(db.receta, "idReceta", "idPaciente", visita.idReceta);
            return View(visita);
        }

        // GET: visitas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visita visita = db.visita.Find(id);
            if (visita == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", visita.idEmpleado);
            ViewBag.idReceta = new SelectList(db.receta, "idReceta", "idPaciente", visita.idReceta);
            return View(visita);
        }

        // POST: visitas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idVisita,idEmpleado,idReceta,fechaLlegada,proximaFecha,motivo,comentario")] visita visita)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visita).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idEmpleado = new SelectList(db.empleado, "idEmpleado", "nombre", visita.idEmpleado);
            ViewBag.idReceta = new SelectList(db.receta, "idReceta", "idPaciente", visita.idReceta);
            return View(visita);
        }

        // GET: visitas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visita visita = db.visita.Find(id);
            if (visita == null)
            {
                return HttpNotFound();
            }
            return View(visita);
        }

        // POST: visitas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            visita visita = db.visita.Find(id);
            db.visita.Remove(visita);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hospital/Hospital/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<html>
<body>

    <div class="jumbotron background-color:transparent !important; bg-info mt-4">
        <h2 class="display-4 text-white text-center">Bienvenido</h2>
        <p class="lead text-white text-center mt-2">Aqui la salud esta primero</p>
        <div class="text-center">
           

        </div>
    </div>


    <div class="row text-center">

        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card bg-info ml-2" style="height: 22rem;">
                <img class="card-img-top" src="~/Content/Media/12354.png" alt="">
                <div class="card-body">
                    <h4 class="card-title text-center text-white">Pasciente</h4>
                    <p class="card-text text-center text-white">
                        Aqui puedes encontrar , a los mejores doctores.

                    </p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Pacientes", "Index", "pacientes", null, new { @class = "btn btn-light" })
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card bg-info mr-4" style="height: 22rem;">
                <img class="card-img-top" src="~/Content/Media/12354.png" alt="">
                <div class="card-body">
                    <h4 class="card-title text-center text-white">Empleados</h4>
                    <p class="card-text text-center text-white">Aqui puedes encontrar , a los mejores doctores.</p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Empleados", "Index", "empleadoes", null, new { @class = "btn btn-light" })
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card bg-info " style="height: 22rem;">
                <img class="card-img-top" src="~/Content/Media/12354.png" alt="">
                <div class="card-body">
                    <h4 class="card-title text-center text-white">Consultas</h4>
                    <p class="card-text text-center text-white">
                        Aqui puedes encontrar , a los mejores doctores.

                    </p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Consultas", "Index", "consultas", null, new { @class = "btn btn-light" })
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <img class="card-img-top" src="~/Content/Media/1hospital.jpg" alt="">
                <div class="card-body">
                    <h4 class="card-title">Citas</h4>
                    <p class="card-text">
                        ¿Quieres empezar a aprender y practicar verbos
                    </p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Citas", "Index", "citas", null, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <img class="card-img-top" src="~/Content/Media/1hospital.jpg" alt="">
                <div class="card-body">
                    <h4 class="card-title">Facturas</h4>
                    <p class="card-text">
                        ¿Quieres empezar a aprender y practicar verbos
                    </p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Facturas", "Index", "facturas", null, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card bg-info" style="height: 22rem;">
                <img class="card-img-top" src="~/Content/Media/12354.png" alt="">
                <div class="card-body">
                    <h4 class="card-title text-center text-white">Visitas</h4>
                    <p class="card-text text-center text-white">
                        Aqui puedes encontrar , a los mejores doctores.
                    </p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Visitas", "Index", "visitas", null, new { @class = "btn btn-light" })
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card bg-info" style="height: 22rem;">
                <img class="card-img-top" src="~/Content/Media/12354.png" alt="">
                <div class="card-body">
                    <h4 class="card-title text-center text-white">Recetas</h4>
                    <p class="card-text text-center text-white">
                        Aqui puedes encontrar , a los mejores doctores.
                    </p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Recetas", "Index", "recetas", null, new { @class = "btn btn-light" })
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card bg-info" style="height: 22rem;">
                <img class="card-img-top" src="~/Content/Media/12354.png" alt="">
                <div class="card-body">
                    <h4 class="card-title text-center text-white">Usuarios</h4>
                    <p class="card-text text-center text-white">
                        Aqui puedes encontrar , a los mejores doctores.
                    </p>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Usuarios", "Index", "usuarios", null, new { @class = "btn btn-light" })
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/content/media/Site.css")

</body>
</html>